FROM ubuntu:14.04

RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 0C49F3730359A14518585931BC711F9BA15703C6

ENV MONGO_MAJOR 3.4
RUN echo "deb [ arch=amd64 ] http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/$MONGO_MAJOR multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.4.list

# Install MongoDB
RUN apt-get update
RUN sudo apt-get install -y mongodb-org=3.4.4 mongodb-org-server=3.4.4 mongodb-org-shell=3.4.4 mongodb-org-mongos=3.4.4 mongodb-org-tools=3.4.4

#System kernel
#RUN echo never >>  /sys/kernel/mm/transparent_hugepage/enabled \
#&& echo never >>  /sys/kernel/mm/transparent_hugepage/defrag

# Create the MongoDB data directory
RUN mkdir -p /usr/local/mongo/conf \
&& mkdir -p /usr/local/mongo/data \
&& mkdir -p /usr/local/mongo/log

# Copy conf
ADD ./conf.d/mongo.conf /usr/local/mongo/conf/mongo.conf
ADD ./prepairation/init.sh /init.sh
ADD ./prepairation/init_slave.sh /init_slave.sh

# Crteate the MongoDB user
RUN useradd -u800 mongod \
&& echo mongod:123456 | chpasswd \
&& chown -R mongod.mongod /usr/local/mongo \
&& chown mongod.mongod /usr/bin/mongod /usr/bin/mongos \
&& chmod a+x /init.sh /init_slave.sh

EXPOSE 27107
USER mongod
ENTRYPOINT ["usr/bin/mongod","-f","/usr/local/mongo/conf/mongo.conf"]
